### ISSUE TITLE
Add input to ignore the dependencies of the build

### ISSUE THREAD

**Issue by adpi2** [scalacenter/sbt-dependency-submission#110]
We can ignore the dependencies of some configurations, with `configs-ignore`, but we cannot ignore the dependencies of the build.

**Comment by armanbilge** [comment]
Would it be possible to provide a pointer how this should be fixed? Truthfully it's not obvious to me how the build dependencies are getting included to begin with, since my understanding was that this is an sbt plugin running in the build and not in the meta-build.

We're planning to rollout the dependency-submission action to hundreds of repos as part of [sbt-typelevel v0.5.0](https://github.com/typelevel/sbt-typelevel/releases/tag/v0.5.0-RC1) and I think this is the one last annoying thing.

**Comment by adpi2** [comment]
> since my understanding was that this is an sbt plugin running in the build and not in the meta-build.

You are right.

I initially planned to report the dependencies of the meta-build. But I did find a good solution and decided to drop the idea.
