### ISSUE TITLE
sbt-dependency-submission failing on Pekko-http

### ISSUE THREAD

**Issue by mdedetrich** [scalacenter/sbt-dependency-submission#156]
See https://github.com/apache/incubator-pekko-http/issues/433 for the error, specifically https://github.com/apache/incubator-pekko-http/actions/runs/7609830392/job/20721867848

**Comment by adpi2** [comment]
Thanks for the report.

It seems there is a resolution error on `pekko-http-tests_3` because it depends on `pekko-http-scalafix-rules` which is not cross-compiled to Scala 3.

 To work around this you can either:
1. Fix your build, not sure how, maybe define empty sources for `pekko-http-scalafix-rules_3`
2. Add `modules_ignore: [pekko-http-tests_3]` in the input of `sbt-dependency-submission` (see [documentation](https://github.com/scalacenter/sbt-dependency-submission#--modules-ignore-optional))
3. Set `on-resolve-failure: warning` in the input of `sbt-dependency-submission` (not documented anywhere except in [here](https://github.com/scalacenter/sbt-dependency-submission/blob/main/action.yml))

**Comment by mdedetrich** [comment]
Thanks, trying solution 2 now. Will close ticket once I confirm it works.

**Comment by mdedetrich** [comment]
Thanks, `modules-ignore` solved the problem. Closing ticket.
