### ISSUE TITLE
Unexpected inclusion of scala library in generated dependency tree

### ISSUE THREAD

**Issue by adamnfish** [scalacenter/sbt-dependency-submission#211]
This workflow finds dependencies that we wouldn't expect, and that we don't find generated by sbt's own dependencyTree command. This is a problem because we are using this workflow to detect vulnerabilities in GitHub via Dependabot and we are seeing vulnerabilities for software dependencies that we don't believe are part of our build.

To demonstrate the issue, we've created an [SSCCE](http://www.sscce.org/) project:

## [guardian/dependency-problem-sscce](https://github.com/guardian/dependency-problem-sscce)

As the README describes, this Scala `3.4.2` program with no dependencies is showing a dependency on the Scala library at version `2.13.12`. We've seen other examples in more complex builds where we're unexpectedly seeing older vulnerable versions of the Scala library as a dependency, which is then showing up as security issues in Dependabot.

Ideally, the dependency tree that the `sbt-dependency-submission` generates would line up with the tree that sbt's own `dependencyTree` command produces. I understand the difference is that unlike dependencyTree, this plugin considers all scopes and asks us to filter the scopes we aren't interested in using the `ignoredConfigs` setting. The script that generates the tree [is providing](https://github.com/guardian/dependency-problem-sscce/blob/main/generate_dependency_trees.sh#L5C67-L5C81) a few scopes to that exclusion list (`scala-doc-tool,scala-tool,test`), perhaps this is missing some other scopes that should be ignored?

## A bit more context

In [the linked SSCCE project](https://github.com/guardian/dependency-problem-sscce/tree/main), we've checked in files that contain the trees generated by each tool.

The dependency JSON that this workflow's plugin generates is here:
https://github.com/guardian/dependency-problem-sscce/blob/main/sbt_dependency_submission_workflow.json

and the sbt dependencyTree output is here:
https://github.com/guardian/dependency-problem-sscce/blob/main/dependency_tree.txt

These files can easily be generated using the [script](https://github.com/guardian/dependency-problem-sscce/blob/main/generate_dependency_trees.sh) in the repository, to recreate the issue.

**Comment by adpi2** [comment]
Hello @adamnfish,

`sbt-dependency-submission` is correct here. The `scala3-library` is just a thin layer on top of the Scala 2 library on which it depends. You can see that [here](https://central.sonatype.com/artifact/org.scala-lang/scala3-library_3/3.4.2/dependencies) or directly in the [pom file of the Scala 3 library](https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.4.2/scala3-library_3-3.4.2.pom):

```xml
<dependency>
  <groupId>org.scala-lang</groupId>
  <artifactId>scala-library</artifactId>
  <version>2.13.12</version>
</dependency>
```

Also some explanation are given [here](https://docs.scala-lang.org/scala3/guides/migration/compatibility-classpath.html) about the compatibility between Scala 2.13 and Scala 3.

In sbt, `dependencyTree` does not print the Scala 2 library, but `fullClasspath` does:
```
sbt:example> dependencyTree
[info] example:example_3:0.1.0-SNAPSHOT
[info]   +-org.scala-lang:scala3-library_3:3.4.2 [S]
[info]   
[success] Total time: 0 s, completed Aug 20, 2024, 10:13:35 AM
sbt:example> show fullClasspath
[info] * Attributed(/home/piquerez/github/scalacenter/example/target/scala-3.4.2/classes)
[info] * Attributed(/home/piquerez/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.4.2/scala3-library_3-3.4.2.jar)
[info] * Attributed(/home/piquerez/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar)
[success] Total time: 0 s, completed Aug 20, 2024, 10:15:00 AM
```

That's because there is a `dependencyTreeIncludeScalaLibrary` [setting](https://github.com/sbt/sbt/blob/2f936295f158117baf9397ce8e9487bf9be8c87e/main/src/main/scala/sbt/plugins/DependencyTreeKeys.scala#L19-L21), that is false by default to avoid too many redundancy in the output of `dependencyTree` (every Scala library depends on the standard library).

Maybe the bug is that `dependencyTreeIncludeScalaLibrary` should also exclude the Scala 3 library.
