### ISSUE TITLE
subproject jars are included in dependency graph

### ISSUE THREAD

**Issue by stevedlawrence** [scalacenter/sbt-dependency-submission#54]
We have an SBT project that has multiple subprojects created out of the same repository. When using sbt-dependency-submission, the jars from each subproject are listed in the dependency graph. But I would expect that these jars would be ignored and only external dependencies listed in the dependency graph.

**Comment by adpi2** [comment]
Thanks for opening this issue.

The subprojects are indeed listed in the dependency graph and that is questionable but I would argue that it is limitation of the dependency view. The structure that we push to the Github API is a graph of dependencies and it would be incorrect to remove some nodes because they are internal. If project A depends on project B which depends on library C, we cannot just remove project B from the graph, or pretend that A directly depends on C.
