### ISSUE TITLE
Got errror jawn.IncompleteParseException: exhausted input

### ISSUE THREAD

**Issue by YunpengDing15** [scalacenter/sbt-dependency-submission#59]
When I use this tool to generate the dependency graph for our sbt project with the default working directory, always got the issue(SBT version in our project is 1.3.13):
![image](https://user-images.githubusercontent.com/59902077/190542907-7f70c769-def5-4750-b473-df31c4699af5.png)

The code is:
![image](https://user-images.githubusercontent.com/59902077/190542989-91d301eb-ccf0-4abf-8341-2c78d543d6a4.png)

Could anyone help with this? thanks!

**Comment by adpi2** [comment]
Thanks for opening this issue.

Here is the bug fix: https://github.com/scalacenter/sbt-dependency-submission/pull/60

Have you considered using a more recent version of sbt?

**Comment by YunpengDing15** [comment]
Thank @adpi2, and actually, I want to ignore one module but seems it not works, could you help with this?
![image](https://user-images.githubusercontent.com/59902077/190605550-bffbbbfd-00da-4f69-9d6e-64ce4984fe09.png)

**Comment by adpi2** [comment]
The pattern for the name of a module is `<project name>_<scala binary version>`

In your project this is probably something like `myob-di-jvm-sdk_2.13`. In your screenshot `0.0.3` is clearly wrong because it is not a Scala binary version. The Scala binary version can be `2.12`, `2.13` or `3` depending on your version.

Also you should see all the names of the modules in the log of the sbt-dependency-action.
